language: ruby
cache: bundler
bundler_args: --without production heroku
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-19mode
env:
  - DB=sqlite
  - DB=mysql
before_install: cp config/database.yml.$DB config/database.yml
# script: "./script/ci/travis-build"
# before_script: "./script/ci/travis-before-build"
branches:
  only:
    - master
notifications:
  recipients:
    - iqvoc@innoq.com
