rvm:
  - 1.8.7-p352
  - 1.9.2-p290
  - jruby-1.6.3

script: "bundle exec rake db:drop db:create db:migrate test:units RAILS_ENV=test --trace"
before_script: "sh travis-build.sh"

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
    