rvm:
  - 1.8.7
  - 1.9.2

script: "ruby ./script/ci/travis-build.rb"
before_script: "ruby ./script/ci/travis-before-build.rb"

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
    