rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

env:
  - DB=sqlite
  - DB=mysql

script: "ruby ./script/ci/travis-build.rb"
before_script: "./script/ci/travis-before-build"

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
