rvm:
  - 1.8.7
  - 1.9.2

script: "./script/ci/travis-build.sh"
before_script: "./script/ci/travis-before-build.sh"

branches:
  only:
    - master

notifications:
  recipients:
    - iqvoc@innoq.com
    